version: "3.9"

services:
  db:
    image: postgres:16
    container_name: idemp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: idempotency
      POSTGRES_USER: idemp
      POSTGRES_PASSWORD: idemp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U idemp -d idempotency"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
