version: "3.9"
services:
db:
image: postgres:16
environment:
POSTGRES_DB: idempotency
POSTGRES_USER: idemp
POSTGRES_PASSWORD: idemp
ports:
  - "5432:5432"
healthcheck:
test: [ "CMD-SHELL", "pg_isready -U idemp -d idempotency" ]
interval: 5s
timeout: 3s
retries: 10
volumes:
  - pgdata:/var/lib/postgresql/data


app:
build: .
depends_on:
db:
condition: service_healthy
environment:
SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/idempotency
SPRING_DATASOURCE_USERNAME: idemp
SPRING_DATASOURCE_PASSWORD: idemp
SPRING_JPA_HIBERNATE_DDL_AUTO: validate
ports:
  - "8080:8080"


volumes:
pgdata: